'use client';

import { useEffect, useMemo, useState } from 'react';
import { ChevronRight, ExternalLink, Focus, Maximize2, Network, ShieldCheck, Sparkles, X } from 'lucide-react';
import { Tag } from '@/components/ui';
import { nodes as fallback, Node } from '@/lib/mock-data';
import { useApp } from '@/components/app-provider';
import { apiFetch } from '@/lib/api';
import { orgIdFor } from '@/lib/org';

type GraphResponse = { nodes: Node[]; edges: { source: string; target: string; weight: number }[] };
type PositionedNode = Node & { gx: number; gy: number };
const NODE_W = 190;
const NODE_H = 66;
function confidenceColor(value: Node['confidence']) { return value === 'Verified' ? 'var(--verified)' : value === 'Configured' ? 'var(--configured)' : 'var(--estimated)'; }
function circuitPath(a: PositionedNode, b: PositionedNode) { const direction = b.gx >= a.gx ? 1 : -1; const sx = a.gx + direction * NODE_W / 2; const tx = b.gx - direction * NODE_W / 2; const bend = Math.max(36, Math.abs(tx - sx) * .34); return `M ${sx} ${a.gy} C ${sx + direction * bend} ${a.gy}, ${tx - direction * bend} ${b.gy}, ${tx} ${b.gy}`; }

export default function Graph() {
  const { org } = useApp();
  const [data, setData] = useState<GraphResponse | null>(null);
  const [selected, setSelected] = useState<Node | null>(fallback[0]);
  const [hovered, setHovered] = useState<string | null>(null);
  const [choke, setChoke] = useState(false);
  const [detail, setDetail] = useState(false);
  useEffect(() => { apiFetch<GraphResponse>(`/api/v1/organizations/${orgIdFor(org)}/graph`).then(graph => { setData(graph); setSelected(graph.nodes[0]); }).catch(() => setData(null)); }, [org]);
  const graph = data || { nodes: fallback, edges: [] };
  const edgePairs = graph.edges.length ? graph.edges.map(edge => [graph.nodes.findIndex(node => node.id === edge.source), graph.nodes.findIndex(node => node.id === edge.target)]).filter(edge => edge[0] >= 0 && edge[1] >= 0) : [[0, 1], [0, 2], [0, 3], [1, 4], [1, 5], [2, 3], [2, 6], [3, 7], [4, 5], [6, 8], [8, 9]];
  const positioned = useMemo<PositionedNode[]>(() => { const grouped: Record<'entry' | 'asset' | 'impact', Node[]> = { entry: [], asset: [], impact: [] }; const laneFor = (node: Node): 'entry' | 'asset' | 'impact' => ['User group', 'Third party', 'Application', 'Internet-facing'].includes(node.type) ? 'entry' : ['Data store', 'Resilience', 'Detection'].includes(node.type) ? 'impact' : 'asset'; graph.nodes.forEach(node => grouped[laneFor(node)].push(node)); return graph.nodes.map(node => { const lane = laneFor(node); const row = grouped[lane].findIndex(item => item.id === node.id); const count = grouped[lane].length; return { ...node, gx: lane === 'entry' ? 120 : lane === 'asset' ? 380 : 640, gy: 170 + ((row + 1) * 390) / (count + 1) }; }); }, [graph.nodes]);
  const selectedIndex = selected ? graph.nodes.findIndex(node => node.id === selected.id) : -1;
  const visibleCount = graph.nodes.filter(node => !choke || ['pay', 'core', 'sso'].includes(node.id)).length;
  const totalRisk = useMemo(() => graph.nodes.reduce((sum, node) => sum + node.risk, 0), [graph.nodes]);

  return <div className="graph-wrap futuristic-graph circuit-graph">
    <div className="graph-grid-overlay" />
    <header className="graph-command-bar"><div className="graph-title-block"><div className="eyebrow"><Network size={12} /> Attack surface intelligence</div><h1>Attack graph</h1><p>{org} · {visibleCount} of {graph.nodes.length} nodes visible · live exposure paths</p></div><div className="graph-command-actions"><span className="graph-live"><i /> Streaming model</span><button className={choke ? 'ghost choke-toggle active' : 'ghost choke-toggle'} onClick={() => setChoke(!choke)}><Focus size={14} /> {choke ? 'Choke points only' : 'Show choke points'}</button></div></header>
    <svg className="graph-svg futuristic-svg circuit-svg" viewBox="0 0 760 650" preserveAspectRatio="none"><defs><filter id="nodeGlow"><feGaussianBlur stdDeviation="5" result="blur" /><feMerge><feMergeNode in="blur" /><feMergeNode in="SourceGraphic" /></feMerge></filter><linearGradient id="edgeFlow" x1="0" x2="1"><stop offset="0" stopColor="#4f46e5" stopOpacity=".12" /><stop offset=".5" stopColor="#22c55e" stopOpacity=".8" /><stop offset="1" stopColor="#4f46e5" stopOpacity=".12" /></linearGradient></defs><text className="lane-label" x="58" y="76">ENTRY POINTS</text><text className="lane-label" x="300" y="76">CRITICAL ASSETS</text><text className="lane-label" x="536" y="76">BUSINESS IMPACT</text><line className="lane-line" x1="58" y1="88" x2="218" y2="88" /><line className="lane-line" x1="300" y1="88" x2="450" y2="88" /><line className="lane-line" x1="536" y1="88" x2="690" y2="88" />{edgePairs.map(([a, b], index) => { const source = positioned[a]; const target = positioned[b]; const connected = selectedIndex === a || selectedIndex === b; return <path key={index} className={`graph-edge futuristic-edge circuit-link ${connected ? 'connected' : ''}`} d={circuitPath(source, target)} />; })}{positioned.map(node => { const active = !choke || ['pay', 'core', 'sso'].includes(node.id); const color = confidenceColor(node.confidence); const focused = selected?.id === node.id || hovered === node.id; const x = node.gx - NODE_W / 2; const y = node.gy - NODE_H / 2; return <g key={node.id} className={`graph-node futuristic-node circuit-node ${focused ? 'focused' : ''}`} opacity={active ? 1 : .12} onMouseEnter={() => setHovered(node.id)} onMouseLeave={() => setHovered(null)} onClick={() => { setSelected(node); setDetail(false); }}><rect className="node-halo" x={x - 8} y={y - 8} width={NODE_W + 16} height={NODE_H + 16} rx="13" fill={color} /><rect className="circuit-card" x={x} y={y} width={NODE_W} height={NODE_H} rx="9" fill="var(--surface)" stroke={color} strokeWidth={focused ? 2.5 : 1.5} filter={focused ? 'url(#nodeGlow)' : undefined} /><rect className="circuit-accent" x={x} y={y} width="5" height={NODE_H} rx="3" fill={color} /><circle className="circuit-port" cx={x} cy={node.gy} r="6" fill="var(--surface)" stroke={color} /><circle className="circuit-port" cx={x + NODE_W} cy={node.gy} r="6" fill="var(--surface)" stroke={color} /><circle className="circuit-status" cx={x + NODE_W - 13} cy={y + 12} r="4" fill={color} /><text className="circuit-node-label" x={x + 18} y={y + 22}>{node.name}</text><text className="circuit-node-type" x={x + 18} y={y + 39}>{node.type} · ₹{(node.risk / 100000).toFixed(0)}L EAL</text>{focused && <text className="node-risk-label" x={x + NODE_W + 12} y={y + NODE_H + 17}>trace active</text>}</g>; })}</svg>
    {selected && !detail && <div className="graph-panel node-detail-panel futuristic-panel"><div className="panel-drag-line" /><div className="section-head"><div><div className="eyebrow">Selected node · live</div><h2>{selected.name}</h2></div><span className="panel-lock" title="Selected node panel stays open"><ShieldCheck size={15} /></span></div><div className="selected-node-meta"><span className="selected-node-orb" style={{ background: confidenceColor(selected.confidence) }} /><div><Tag value={selected.confidence} /><small>{selected.type} · {org}</small></div></div><div className="node-stat-highlight"><span>Risk contribution</span><strong>₹{(selected.risk / 100000).toFixed(0)}L</strong><small>{((selected.risk / (totalRisk || 1)) * 100).toFixed(1)}% of mapped exposure</small></div><div className="node-mini-grid"><div><span>Attached CVEs</span><strong>{String(selected.cves.length).padStart(2, '0')}</strong></div><div><span>Critical paths</span><strong>03</strong></div></div><div className="root-cause-callout"><div><Sparkles size={14} /><strong>Root cause trace</strong></div><p>{selected.cves.length ? `${selected.cves[0]} is the leading entry condition for this node.` : 'Control coverage and path connectivity are the primary drivers for this node.'}</p></div><p className="panel-copy">Select another node to trace its upstream entry points and downstream exposure. Open the full asset view for control-level evidence.</p><button className="primary full-action" onClick={() => setDetail(true)}><Maximize2 size={14} /> Open node detail <ChevronRight size={14} /></button></div>}
    {selected && detail && <div className="graph-panel node-detail-panel detail-view futuristic-panel"><div className="panel-drag-line" /><div className="section-head"><div><div className="eyebrow">Asset intelligence · {org}</div><h2>{selected.name}</h2></div><button className="icon-btn" onClick={() => setDetail(false)}><X size={15} /></button></div><div className="detail-hero"><span className="detail-node-icon"><ShieldCheck size={20} /></span><div><Tag value={selected.confidence} /><p>{selected.type} · live API asset</p></div></div><div className="detail-grid"><div><span>Risk contribution</span><strong>₹{(selected.risk / 100000).toFixed(0)}L</strong></div><div><span>Severity</span><strong className="severity-high">High</strong></div><div><span>Open paths</span><strong>03</strong></div></div><section className="detail-section"><h3>Contributing vulnerabilities</h3>{selected.cves.length ? selected.cves.map(cve => <div className="vuln-row" key={cve}><div><strong>{cve}</strong><small>Remote code execution · KEV monitored</small></div><span className="tag configured">CVSS 8.1 · EPSS 0.42</span></div>) : <p style={{ color: 'var(--muted)' }}>No contributing CVEs currently attached.</p>}</section><section className="detail-section"><h3>Controls attached</h3><div className="control-chip"><ShieldCheck size={14} color="var(--verified)" /><span>MFA on privileged access</span><Tag value="Verified" /></div><div className="control-chip"><ShieldCheck size={14} color="var(--configured)" /><span>Network segmentation</span><Tag value="Configured" /></div></section><button className="ghost full-action" onClick={() => setDetail(false)}><ExternalLink size={14} /> Back to graph selection</button></div>}
  </div>;
}
